apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-t-core
spec:
  template:
    metadata:
      name: pod-t-core
      labels:
        app: t-core
    spec:
      containers:
        - name: t-core-container
          image: acmlira/t-core:dev
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: configmap-t-core
  replicas: 3
  selector:
    matchLabels:
      app: t-core